Repository BiomedEngineering2ndBrain/GIT-Transport-Model, pull requests merged in 2023-11, with the labels that each got.

#22 Code staging
  .DS_Store
  Code/Aterial.m
  Code/Food.m
  Code/GutCalc.m
  Code/Main.m
  README.md
Labels: enhancement

#27 removed unnecessary folders
  Research/Inputs/Colon/.empty
  Research/Inputs/Mouth/.empty
  Research/Inputs/Oesophagus/.empty
  Research/Inputs/Small intestine/.empty
  Research/Inputs/Stomach/.empty
  Research/Outputs/Colon/.empty
  Research/Outputs/Mouth/.empty
  Research/Outputs/Oesophagus/.empty
  Research/Outputs/Small intestine/.empty
  Research/Outputs/Stomach/.empty
Labels: documentation

#31 25 document first code draft
  .gitignore
  .obsidian/workspace.json
  .vscode/settings.json
  Attachments/Pasted image 20231111150050.png
  Code/docs/Food.md
  Code/docs/GlycemicLoad.md
  Code/docs/README.md
  Code/docs/find_gl_glucose.md
  Code/src/Food.m
  Code/src/GlycemicLoad.m
  Code/src/GutCalc.m
  Code/src/find_gl_glucose.m
  Research-notes/Absorption in the GIT.md
  Research-notes/THEORY OF OXYGEN TRANSPORT TO TISSUE.md
  Research-notes/bloodflowresponsesceliacsuperiormesentericarteriesinitialphasedigestion-someya.pdf
  Research-notes/circulationoverview-granger.pdf
  Research-notes/costchewingenergeticsevolutionarysignificancemasticationhumans-vancasteren.pdf
  Research-notes/definingcriticallimitoxygenextractionhumansmallintestine-desai.pdf
  Research-notes/developmentpredictionmodelestimateglycemicloadreadytoeatmeals-lee.pdf
  Research-notes/dynamicsglucoseinsulinconcentrationconnectedcellcyclemodeldevelopmentanalysis-gallenberger.pdf
  Research-notes/effectsmealglycemicloadbloodglucoselevelsadultsdifferentbodymassindexes-yalcin.pdf
  Research-notes/enhancingbloodglucosepredictionmealabsorptionphysicalexerciseinformation-liu.pdf
  Research-notes/glucoseuptakesaturationexplainsglucosekineticsprofilesmeasureddifferenttests-bizzotto.pdf
  Research-notes/partialpressureoxygenhumanbodygeneralreview-ortiz-prado.pdf
  Research-notes/postprandialbloodglucosediabetescareamericandiabetesassociation-.pdf
  Research-notes/postprandialinsulintriglyceridesdifferentbreakfastmealchallengesusefingerstickcapillarydriedbloodspotsstudypostprandialdysmetabolism-kapur.pdf
  Research-notes/regulationintestinalglucoseabsorptionionchannelstransporters-chen.pdf
  Research-notes/rolesgutglucosehomeostasisdiabetescareamericandiabetesassociation-.pdf
  Research-notes/silicomodellingmasstransferabsorptionhumangut-moxon.pdf
  Research-notes/simplerobustmethodestimatingglucoserateappearancemixedmeals-herrero.pdf
  Research-notes/theoryoxygentransporttissue-popel.pdf
  Research/Absorption in the GIT.md
  Research/Development of a Prediction Model to Estimate the Glycemic Load of Ready-to-EatMeals.pdf
  Research/Enhancing Blood Glucose Prediction with Meal Absorption and Physical Exercise Information.pdf
  Research/In silico modelling of mass transfer & absorption in the human gut.pdf
  Research/Postprandial Blood Glucose.pdf
  Research/Postprandial Insulin and Triglycerides after Different Breakfast Meal.pdf
  Research/Regulation of Intestinal Glucose Absorption by Ion.pdf
  Research/Roles Of the Gut in Glucose Homeostasis.pdf
  Research/The cost of chewing- The energetics and evolutionary significance of mastication in humans.pdf
  Research/The effects of meal glycemic load on blood glucose levels of adults with different body mass indexes.pdf
  Research/bizzotto-et-al-2016-glucose-uptake-saturation-explains-glucose-kinetics-profiles-measured-by-different-tests.pdf
  Research/circulation_overview_stats.pdf
  Research/crit_limit_o2_extraction_av_diff.pdf
  Research/glucose_insulin(complicated).pdf
  Research/partial_p_o2_values.pdf
  Research/someya-et-al-2008-blood-flow-responses-in-celiac-and-superior-mesenteric-arteries-in-the-initial-phase-of-digestion.pdf
  Untitled.txt
Labels: documentation, enhancement

#33 25 document first code draft
  .obsidian/workspace.json
  Code/src/Food.m
  Code/src/GutCalc.m
  Code/src/Main.asv
  Code/src/Main.m
Labels: documentation, enhancement

#37 34 glucose model
  Code/src/Arterial.m
  Code/src/Food.m
  Code/src/GUT_PARAMS.m
  Code/src/GutCalc.m
  Code/src/Main.asv
  Code/src/Main.m
  Code/src/OverallLoop.m
  Code/src/check_meal_time.m
  Code/src/delta_arterial.m
  Code/src/delta_gut.m
  Code/src/find_gl_glucose.m
  Code/src/food.m
  Code/src/glucose/.empty
  Code/src/glucose_output_model.m
  Code/src/glycemic_load.m
  Code/src/oxygen_co2/.empty
  Research/GITTransportModel.bib
Labels: enhancement

#44 Merge code staging into main with newest updates
  Code/Code.md
  Code/src/GUT_PARAMS.m
  Code/src/GutCalc.m
  Code/src/O2_Absorption.m
  Code/src/O2_CO2.m
  Code/src/glucose_aborption_2.m
  Code/src/glucose_absorption.m
  Code/src/glucose_absorption_3.m
  Code/src/sigfit.m
Labels: enhancement

#72 Updated CHANGELOG
  CHANGELOG.md
Labels: update-changelog

#83 Merge Code staging to main
  Code/src/O2_Absorption.m
  Code/src/O2_fed_fasting.m
  Code/src/testing_O2.m
Labels: enhancement
